-- ============================================================
-- LinkWork Task / Workstation / Execution Flow Schema
-- ============================================================

CREATE TABLE IF NOT EXISTS linkwork_workstation (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    workstation_no  VARCHAR(64)  NOT NULL COMMENT '岗位编号',
    name            VARCHAR(128) NOT NULL COMMENT '岗位名称',
    description     TEXT         COMMENT '岗位描述',
    category        VARCHAR(64)  COMMENT '分类',
    icon            VARCHAR(255) COMMENT '图标 URL',
    image           VARCHAR(512) COMMENT '容器镜像',
    prompt          LONGTEXT     COMMENT '系统提示词',
    status          VARCHAR(32)  NOT NULL DEFAULT 'active' COMMENT '状态',
    config_json     JSON         COMMENT '扩展配置',
    is_public       TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否公开',
    max_employees   INT          NOT NULL DEFAULT 1 COMMENT '最大并发执行数',
    creator_id      VARCHAR(64)  NOT NULL,
    creator_name    VARCHAR(128),
    updater_id      VARCHAR(64),
    updater_name    VARCHAR(128),
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted      TINYINT(1)   NOT NULL DEFAULT 0,
    UNIQUE KEY uk_workstation_no (workstation_no),
    INDEX idx_creator (creator_id),
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='岗位表';

CREATE TABLE IF NOT EXISTS linkwork_user_favorite_workstation (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id         VARCHAR(64)  NOT NULL,
    workstation_id  BIGINT       NOT NULL,
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_ws (user_id, workstation_id),
    INDEX idx_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户收藏岗位';

CREATE TABLE IF NOT EXISTS linkwork_task (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_no         VARCHAR(64)  NOT NULL COMMENT '任务编号',
    workstation_id  BIGINT       NOT NULL,
    workstation_name VARCHAR(128),
    prompt          LONGTEXT     NOT NULL COMMENT '任务内容',
    status          VARCHAR(32)  NOT NULL DEFAULT 'pending' COMMENT '任务状态',
    image           VARCHAR(512) COMMENT '容器镜像',
    selected_model  VARCHAR(64)  COMMENT '选用模型',
    assembly_id     BIGINT       COMMENT '装配 ID',
    config_json     JSON         COMMENT '扩展配置',
    source          VARCHAR(32)  COMMENT '来源: web/api/cron',
    cron_job_id     BIGINT       COMMENT '关联定时任务 ID',
    creator_id      VARCHAR(64)  NOT NULL,
    creator_name    VARCHAR(128),
    creator_ip      VARCHAR(64),
    updater_id      VARCHAR(64),
    updater_name    VARCHAR(128),
    tokens_used     INT          DEFAULT 0,
    input_tokens    INT          DEFAULT 0,
    output_tokens   INT          DEFAULT 0,
    request_count   INT          DEFAULT 0,
    token_limit     BIGINT       DEFAULT 0,
    usage_percent   DECIMAL(5,2) DEFAULT 0,
    duration_ms     BIGINT       DEFAULT 0,
    report_json     JSON         COMMENT '任务执行报告',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted      TINYINT(1)   NOT NULL DEFAULT 0,
    UNIQUE KEY uk_task_no (task_no),
    INDEX idx_ws (workstation_id),
    INDEX idx_creator (creator_id),
    INDEX idx_status (status),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务表';

CREATE TABLE IF NOT EXISTS linkwork_task_git_auth (
    task_id         VARCHAR(64)  NOT NULL PRIMARY KEY COMMENT '任务ID (task_no)',
    user_id         VARCHAR(64)  NOT NULL,
    provider        VARCHAR(32)  NOT NULL COMMENT 'git 提供商: gitlab/github',
    git_auth_id     BIGINT       COMMENT '关联的 git 授权记录 ID',
    expires_at      DATETIME     COMMENT '令牌过期时间',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted      TINYINT(1)   NOT NULL DEFAULT 0,
    INDEX idx_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务 Git 授权';

CREATE TABLE IF NOT EXISTS linkwork_cron_job (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    job_name              VARCHAR(128) NOT NULL COMMENT '定时任务名称',
    creator_id            VARCHAR(64)  NOT NULL,
    creator_name          VARCHAR(128),
    workstation_id        BIGINT       NOT NULL,
    workstation_name      VARCHAR(128),
    model_id              VARCHAR(64),
    file_ids_json         JSON         COMMENT '关联文件 ID 列表',
    schedule_type         VARCHAR(32)  NOT NULL COMMENT 'cron/interval/once',
    cron_expr             VARCHAR(128) COMMENT 'cron 表达式',
    interval_ms           BIGINT       COMMENT '间隔毫秒',
    run_at                DATETIME     COMMENT '一次性执行时间',
    timezone              VARCHAR(64)  DEFAULT 'Asia/Shanghai',
    task_content          LONGTEXT     NOT NULL COMMENT '任务内容',
    enabled               TINYINT(1)   NOT NULL DEFAULT 1,
    delete_after_run      TINYINT(1)   NOT NULL DEFAULT 0,
    max_retry             INT          NOT NULL DEFAULT 0,
    consecutive_failures  INT          NOT NULL DEFAULT 0,
    next_fire_time        DATETIME     COMMENT '下次触发时间',
    notify_mode           VARCHAR(32)  COMMENT 'none/dingtalk/webhook',
    notify_target         VARCHAR(512) COMMENT '通知目标',
    total_runs            INT          NOT NULL DEFAULT 0,
    last_run_time         DATETIME,
    last_run_status       VARCHAR(32),
    created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted            TINYINT(1)   NOT NULL DEFAULT 0,
    INDEX idx_creator (creator_id),
    INDEX idx_ws (workstation_id),
    INDEX idx_next_fire (enabled, next_fire_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='定时任务表';

CREATE TABLE IF NOT EXISTS linkwork_cron_job_run (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    cron_job_id       BIGINT       NOT NULL,
    task_no           VARCHAR(64)  COMMENT '关联任务编号',
    creator_id        VARCHAR(64)  NOT NULL,
    workstation_id    BIGINT       NOT NULL,
    status            VARCHAR(32)  NOT NULL DEFAULT 'pending',
    trigger_type      VARCHAR(32)  NOT NULL DEFAULT 'scheduled' COMMENT 'scheduled/manual',
    planned_fire_time DATETIME,
    started_at        DATETIME,
    finished_at       DATETIME,
    duration_ms       BIGINT,
    error_message     TEXT,
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_cron_job (cron_job_id),
    INDEX idx_status (status),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='定时任务执行记录';

CREATE TABLE IF NOT EXISTS linkwork_approval (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    approval_no     VARCHAR(64)  NOT NULL COMMENT '审批编号',
    task_no         VARCHAR(64)  NOT NULL,
    request_id      VARCHAR(128) COMMENT '请求幂等 ID',
    task_title      VARCHAR(512) COMMENT '任务标题',
    action          VARCHAR(128) NOT NULL COMMENT '待审批动作',
    description     TEXT         COMMENT '审批描述',
    risk_level      VARCHAR(32)  COMMENT 'low/medium/high/critical',
    status          VARCHAR(32)  NOT NULL DEFAULT 'pending' COMMENT 'pending/approved/rejected/expired',
    decision        VARCHAR(32)  COMMENT '审批决定',
    comment         TEXT         COMMENT '审批意见',
    operator_id     VARCHAR(64),
    operator_name   VARCHAR(128),
    operator_ip     VARCHAR(64),
    expired_at      DATETIME     COMMENT '审批过期时间',
    decided_at      DATETIME,
    creator_id      VARCHAR(64)  NOT NULL,
    creator_name    VARCHAR(128),
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted      TINYINT(1)   NOT NULL DEFAULT 0,
    UNIQUE KEY uk_approval_no (approval_no),
    INDEX idx_task (task_no),
    INDEX idx_status (status),
    INDEX idx_creator (creator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批记录表';
