CREATE TABLE IF NOT EXISTS linkwork_skill (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    skill_no        VARCHAR(32)  NOT NULL,
    name            VARCHAR(64)  NOT NULL,
    display_name    VARCHAR(128) DEFAULT NULL,
    description     TEXT         DEFAULT NULL,
    implementation  TEXT         DEFAULT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'draft',
    is_public       TINYINT(1)   NOT NULL DEFAULT 0,
    branch_name     VARCHAR(128) DEFAULT NULL,
    latest_commit   VARCHAR(64)  DEFAULT NULL,
    last_synced_at  DATETIME     DEFAULT NULL,
    creator_id      VARCHAR(32)  DEFAULT NULL,
    creator_name    VARCHAR(64)  DEFAULT NULL,
    updater_id      VARCHAR(32)  DEFAULT NULL,
    updater_name    VARCHAR(64)  DEFAULT NULL,
    created_at      DATETIME     DEFAULT NULL,
    updated_at      DATETIME     DEFAULT NULL,
    is_deleted      TINYINT(1)   DEFAULT 0,
    UNIQUE INDEX uk_skill_no   (skill_no),
    UNIQUE INDEX uk_skill_name (name),
    INDEX idx_skill_status     (status),
    INDEX idx_skill_visibility (is_deleted, status, is_public, creator_id)
);
