CREATE TABLE IF NOT EXISTS `robot_mcp_server` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `mcp_no` VARCHAR(64) NULL,
  `name` VARCHAR(128) NOT NULL,
  `endpoint` VARCHAR(1024) NULL,
  `description` TEXT NULL,
  `visibility` VARCHAR(32) NULL DEFAULT 'private',
  `status` VARCHAR(32) NULL DEFAULT 'active',
  `type` VARCHAR(32) NULL DEFAULT 'stdio',
  `url` VARCHAR(1024) NULL,
  `headers` JSON NULL,
  `network_zone` VARCHAR(64) NULL,
  `health_check_url` VARCHAR(1024) NULL,
  `health_latency_ms` INT NULL,
  `health_message` VARCHAR(512) NULL,
  `consecutive_failures` INT NULL DEFAULT 0,
  `version` VARCHAR(64) NULL,
  `tags` JSON NULL,
  `last_health_at` DATETIME NULL,
  `config_json` JSON NULL,
  `creator_id` VARCHAR(128) NULL,
  `creator_name` VARCHAR(255) NULL,
  `updater_id` VARCHAR(128) NULL,
  `updater_name` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_name` (`name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `robot_mcp_user_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `mcp_server_id` BIGINT NOT NULL,
  `headers` JSON NULL,
  `url_params` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_mcp_server_id` (`mcp_server_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
