schedule:
  images:
    agent: ${SCHEDULE_AGENT_IMAGE:}
    runner: ${RUNNER_IMAGE:}

image-build:
  enabled: ${IMAGE_BUILD_ENABLED:true}
  push-enabled: ${IMAGE_PUSH_ENABLED:false}
  default-agent-base-image: ${DEFAULT_AGENT_BASE_IMAGE:}
  registry: ${IMAGE_REGISTRY:}
  registry-username: ${IMAGE_REGISTRY_USERNAME:}
  registry-password: ${IMAGE_REGISTRY_PASSWORD:}
  auto-load-to-kind: ${LINKWORK_BUILD_LOCAL_LOAD_ENABLED:true}
  kind-cluster-name: ${LINKWORK_BUILD_KIND_CLUSTER_NAME:}
  kind-load-timeout: ${KIND_LOAD_TIMEOUT:600}
  local-cleanup-enabled: ${IMAGE_LOCAL_CLEANUP_ENABLED:true}
  local-image-retention-hours: ${IMAGE_LOCAL_RETENTION_HOURS:24}
  local-cleanup-cron: ${IMAGE_LOCAL_CLEANUP_CRON:0 40 * * * *}
  kind-prune-enabled: ${IMAGE_KIND_PRUNE_ENABLED:true}
